### ISSUE TITLE
download current video/audio

### ISSUE THREAD

**Issue by icha1** [cvzi/mpv-youtube-upnext#1]
Is it possible to modify the script so it grabs the current video url and download its audio?

**Comment by cvzi** [comment]
I guess it would be easy to do. Do you happen to know if youtube-dl supports downloading only audio?

**Comment by icha1** [comment]
That would be great. Yes with the -x or --extract-audio option (same) . It converts video files to audio-only files

**Comment by cvzi** [comment]
Then I should be able to do it. I don't really "know" Lua programming language so I guess it won't hurt to practice a little bit :D

**Comment by icha1** [comment]
I have some JS experience. So let me know if I can help.

**Comment by cvzi** [comment]
Here's a first try 
https://github.com/cvzi/mpv-youtube-download
