### ISSUE TITLE
Add to playlist?

### ISSUE THREAD

**Issue by 2084x** [cvzi/mpv-youtube-upnext#10]
Is there a way to add the selected recommended video to the playlist, rather than have it play immediately?

**Comment by cvzi** [comment]
There is not but I think I can add that feature

**Comment by cvzi** [comment]
By pressing space instead of enter, it should now be added to the playlist. The menu can then be closed with Escape (or Ctrl+u).

**Comment by 2084x** [comment]
It works! And you can queue multiple vids! Thanks so much.
