### ISSUE TITLE
Dim player when menu is open

### ISSUE THREAD

**Issue by 2084x** [cvzi/mpv-youtube-upnext#13]
# Feature request: 

Dim the player when the menu is open to increase readability, similar to how [quality menu](https://github.com/christoph-heinrich/mpv-quality-menu) now does.

Relevant [commit](https://github.com/christoph-heinrich/mpv-quality-menu/commit/501794bfbef468ee6a61e54fc8821fe5cd72c4ed).

**Comment by cvzi** [comment]
Thanks! 🙂

**Comment by 2084x** [comment]
Legend.
