### ISSUE TITLE
failed to get upnext list: error=-3 

### ISSUE THREAD

**Issue by LampPrinter** [cvzi/mpv-youtube-upnext#17]
Works fine when I open a new YouTube URL in mpv.

But when using in conjunction with https://github.com/Eisa01/mpv-scripts/blob/master/scripts/SimpleHistory.lua
on resuming a URL from history, I get "failed to get upnext list: error=-3"

**Comment by cvzi** [comment]
Can you please try this version, it will show some more information about the error:

https://gist.githubusercontent.com/cvzi/d5f8cf671bf648a90eadf6f1a5b53edd/raw/a7b8067329ce9389c58ea17d8dec09c8fea627df/youtube-upnext.lua

**Comment by LampPrinter** [comment]
12.533][e][youtube_upnext] download_upnext: url='https://youtube.com/watch?v=l44aHEwjUgU'
[  12.533][e][youtube_upnext]                  post_data='nil' 
[  12.533][e][youtube_upnext] exec: wget -q -O - --load-cookies  --save-cookies  --keep-session-cookies https://youtube.com/watch?v=l44aHEwjUgU 
[  12.533][d][cplayer] Run command: subprocess, flags=64, args=[args="wget,-q,-O,-,--load-cookies,,--save-cookies,,--keep-session-cookies,https://youtube.com/watch?v=l44aHEwjUgU", playback_only="yes", capture_size="67108864", capture_stdout="yes", capture_stderr="no", detach="no", env="", stdin_data="", passthrough_stdin="no"]
[  12.545][e][youtube_upnext] wget output 
[  12.545][e][youtube_upnext] failed to get upnext list: error=-3 
[  12.545][d][youtube_upnext] Invidious url:https://invidious.xyz/api/v1/videos/l44aHEwjUgU 
[  12.545][d][cplayer] Run command: subprocess, flags=64, args=[args="wget,-q,-O,-,https://invidious.xyz/api/v1/videos/l44aHEwjUgU", playback_only="yes", capture_size="67108864", capture_stdout="yes", capture_stderr="no", detach="no", env="", stdin_data="", passthrough_stdin="no"]
[  12.552][e][youtube_upnext] failed to get invidious: error=-3

**Comment by cvzi** [comment]
I think the `-3` means that is doesn't find the `wget` command. But that doesn't make sense if it works for new urls.

What OS are you using?

**Comment by LampPrinter** [comment]
Yes, it is an issue on Apple Silicon apps. 
mpv looks inside /usr/local/bin and not /opt/homebrew/bin

I ran "sudo ln -s /opt/homebrew/bin/wget /usr/local/bin/wget"
Now both cases working fine.

I was using Alfred to extract URL and run script "mpv URL". Anything run through terminal seems to pick up paths fine.

**Comment by cvzi** [comment]
I changed it so that it shows "wget not found" if that error `-3` occurs. That should be better if someone else has this problem as well.
