### ISSUE TITLE
It does not work on playlist

### ISSUE THREAD

**Issue by toprak** [cvzi/mpv-youtube-upnext#21]
I have a playlist and when I open the first video of it I do ctrl u but results are videos that are not in my playlist.  made fetch_on_start=no  in 2 files but still same also pg down and and pg up does not move

**Comment by cvzi** [comment]
The script doesn't do anything special for playlists, it just shows the videos that the youtube.com website suggests on the right side of the current video. Those are sometimes in the playlist and sometimes not.

Page down/up is not supported, if the list doesn't fit on your screen, you can use a smaller font size. Change this line 52:
https://github.com/cvzi/mpv-youtube-upnext/blob/ba6d9ff95347bbf2d577ace2e2c46caa823a8a6a/youtube-upnext.lua#L45-L52
For example to font size "25" like this:
```
    style_ass_tags = "{\\fnmonospace\\fs25}",
```

**Comment by toprak** [comment]
@cvzi oh! big misunderstanding, I apologize.
