### ISSUE TITLE
option to use previous like next aftar use recent

### ISSUE THREAD

**Issue by candrapersada** [cvzi/mpv-youtube-upnext#23]
is there any option to use previous button like next button aftar use recent?

**Comment by cvzi** [comment]
I will look into it

**Comment by cvzi** [comment]
Do you mean this button?
![Screenshot 2023-03-10 152614](https://user-images.githubusercontent.com/8470684/224341166-2c24f5a1-8953-4d10-82e5-3029a55195eb.png)

**Comment by candrapersada** [comment]
yes

**Comment by cvzi** [comment]
Can you please check if this works:
https://github.com/cvzi/mpv-youtube-upnext/blob/previous_button_playlist/youtube-upnext.lua

**Comment by candrapersada** [comment]
`[youtube_upnext] Lua error: ...mpv/portable_config/scripts/youtube-upnext.lua:8: unexpected symbol near '<'` in Windows

**Comment by cvzi** [comment]
Try copy paste code from here: https://raw.githubusercontent.com/cvzi/mpv-youtube-upnext/previous_button_playlist/youtube-upnext.lua

**Comment by candrapersada** [comment]
> Try copy paste code from here: https://raw.githubusercontent.com/cvzi/mpv-youtube-upnext/previous_button_playlist/youtube-upnext.lua

how to use previous?

**Comment by cvzi** [comment]
The button should work now, or with keyboard `<`

> ![Screenshot 2023-03-10 152614](https://user-images.githubusercontent.com/8470684/224341166-2c24f5a1-8953-4d10-82e5-3029a55195eb.png)

**Comment by candrapersada** [comment]
but no working in `uosc.lua`
![gambar](https://user-images.githubusercontent.com/36833664/224452999-9b906437-a48a-4580-825c-44fca0495d0d.png)

**Comment by cvzi** [comment]
I think I misunderstood what you want. Can you explain again, what exactly you want to happen?

**Comment by candrapersada** [comment]
how to use keyboard <

**Comment by cvzi** [comment]
(I is also `<` in uosc)

But I meant, I misunderstood the whole issue. Can you explain what you want to happen? What do you want to see in the playlist?

**Comment by candrapersada** [comment]
there is no previous from `4 to 3` in the playlist but in next there is from `4 to 5`
![gambar](https://user-images.githubusercontent.com/36833664/224454228-3eb1dead-6cae-4f6f-83c1-a6716d347737.png)

**Comment by cvzi** [comment]
I think that is generally not possible. Youtube website doesn't contain information about the previous video.

The script just takes the recommended videos that appear on the right side on Youtube website. You can see the whole list when you press Ctrl + u
If the previous video appears in the list, the script still can't know that it is the "previous" video, it is just one of the recommended videos.
If the previous video doesn't appear in that list, than there is no way to retrieve it at all.

**Comment by candrapersada** [comment]
![gambar](https://user-images.githubusercontent.com/36833664/224454964-935d3506-28d9-4ab3-ba25-39518f158deb.png)
there is no previous from `4 to 3` aftar use recent but in next there is from `4 to 5` aftar use recent
![gambar](https://user-images.githubusercontent.com/36833664/224454228-3eb1dead-6cae-4f6f-83c1-a6716d347737.png)

**Comment by cvzi** [comment]
I see. I don't really know how that works, I have to look it up. 
How do you load such a playlist? (I don't use playlists myself)

**Comment by candrapersada** [comment]
> How do you load such a playlist? (I don't use playlists myself)

`mpv --ytdl-raw-options=yes-playlist= <URL Youtube Playlist>`

**Comment by cvzi** [comment]
Ok thanks. I will take a look when I have some more time.

**Comment by cvzi** [comment]
This would be too much for this script. The script would have to save every playlist to a file and then try to find the correct playlist when a video is played again. That is not really what this script is made for.
Maybe ask the author of whatever 'recent' script that you use to add that feature.

**Comment by candrapersada** [comment]
> That is because the history and bookmark saves the file but not the playlist.
> 
> You cannot bookmark a playlist, you can only bookmark the file.
> 
> Sadly, this is related to https://github.com/Eisa01/mpv-scripts/issues/77 which has been marked as limitations from mpv developers.
