### ISSUE TITLE
[Feature Request]:  Integrate this script with UOSC's menu

### ISSUE THREAD

**Issue by NaiveInvestigator** [cvzi/mpv-youtube-upnext#26]
lol here we go again. If uosc is installed it would use uosc's menu, otherwise use the default menu.
Would be an awesome option for ppl who use uosc!

https://github.com/tomasklaen/uosc#message-handlers

Hope you consider this feature request!

**Comment by cvzi** [comment]
I already though about it, just didn't have the time yet

**Comment by NaiveInvestigator** [comment]
Looking forward to that update when you have the time!!

**Comment by cvzi** [comment]
Please test it: https://github.com/cvzi/mpv-youtube-upnext/raw/uosc/youtube-upnext.lua

**Comment by candrapersada** [comment]
how to even deeper UI integration to the `contols=` option in `uosc.conf`?

**Comment by NaiveInvestigator** [comment]
It works flawlessly!! Tried all 3 buttons and worked as expected.

![image](https://user-images.githubusercontent.com/72654596/226327453-efc74891-dd75-4add-a29a-aa93f06c0434.png)

**Comment by NaiveInvestigator** [comment]
> how to even deeper UI integration to the `contols=` option in `uosc.conf`?

read the text above controls=, it explains in detail how it works.
