### ISSUE TITLE
lua clashed with `youtube-search`

### ISSUE THREAD

**Issue by omaru-ok** [cvzi/mpv-youtube-upnext#27]
i use youtube-search in mpv https://github.com/willswats/mpv-youtube-search

but the problem occurs when `youtube-upnext` is installed , the input feild is not responding 
or more to say https://github.com/CogentRedTester/mpv-user-input is gettign `infected`

**what does it mean?**
both the scirpt `youtube-search` & `youtube-upnext` arent' compatible for now 
make changes so it can support :( 
both are needed

**Comment by omaru-ok** [comment]
re-creating the issue 
1. install `mpv-youtube-search.lua` as [instructed ](https://github.com/willswats/mpv-youtube-search#installation) 
2.  check if it correctly work , with `ALT+s`  to change the list 
3. install youtube-upnext   **there** the issue startes
4. mpv no longer reponsed to whatever u put into `ALT+s`

**Comment by cvzi** [comment]
It seems to work for me, I see no difference with or without youtube-upnext installed.

What exactly happens for you? You can still type and it shows up, but when you press Enter it doesn't search?

**Comment by omaru-ok** [comment]
weird    at my side also fixed ,?  
idk how
