### ISSUE TITLE
why use wget instead of using curl or aria2?

### ISSUE THREAD

**Issue by candrapersada** [cvzi/mpv-youtube-upnext#28]
why do you use `wget` instead of `curl` or `aria2c`?

**Comment by cvzi** [comment]
I don't know the others, what's the difference?

**Comment by candrapersada** [comment]
if curl is available by default in windows 10+

**Comment by cvzi** [comment]
I will check how to use curl

**Comment by cvzi** [comment]
I added curl as standard, with a fallback to wget.
Please test it: https://github.com/cvzi/mpv-youtube-upnext/raw/uosc/youtube-upnext.lua

**Comment by candrapersada** [comment]
it works fine without install latest version in Windows 10+
```
curl 7.79.1 (Windows) libcurl/7.79.1 Schannel
Release-Date: 2021-09-22
Protocols: dict file ftp ftps http https imap imaps pop3 pop3s smtp smtps telnet tftp
Features: AsynchDNS HSTS IPv6 Kerberos Largefile NTLM SPNEGO SSL SSPI UnixSockets
```
