### ISSUE TITLE
Bug: [youtube_upnext] parse_json failed: error 

### ISSUE THREAD

**Issue by egils-consulting** [cvzi/mpv-youtube-upnext#3]
$ mpv https://www.youtube.com/watch?v=ipAnwilMncI 
-> resulted in the error without me doing anything
I'm on archlinux32 with wget installed

**Comment by cvzi** [comment]
I cannot reproduce it right now. Everything works fine for me.

I assume the Youtube page has changed and Youtube is slowly rolling out an update. You get the new version of the page while I still get the old version.
Probably that's the reason for #2 as well. 

You could download the youtube website with "wget https://www.youtube.com/watch?v=ipAnwilMncI" and post it somewhere, then I could compare it

**Comment by cvzi** [comment]
I have updated the script. Please go ahead and test the new version.

**Comment by egils-consulting** [comment]
Thanks, I'll pull in the changes and write how it went. 😃
