### ISSUE TITLE
[Feature Request] Add videos not longer than <n> minutes to playlist 🚀

### ISSUE THREAD

**Issue by FatalError93** [cvzi/mpv-youtube-upnext#33]
Request: Make script load videos not longer than `<n>` minutes only
Current state: When playing a music link video in mpv your script appends only mixes longer than 20 minutes

What would be nice is if it's possible to toggle it to only append shorter videos (say less than `<n>` minutes) to playlist

If it's easy .lua edit please reply how since I'm not as good at scripting as I'm good at yanking

**Comment by cvzi** [comment]
I have checked and the video length is easy to retrieve.
I will add it when I have some time.

**Comment by cvzi** [comment]
I added options for it to the config, please test it.

https://github.com/cvzi/mpv-youtube-upnext/blob/64da48ffb8b92f3a2bf6872c64c6c2fcf98877c9/youtube-upnext.lua#L103-L110

https://github.com/cvzi/mpv-youtube-upnext/blob/64da48ffb8b92f3a2bf6872c64c6c2fcf98877c9/youtube-upnext.conf#L83-L90

**Comment by FatalError93** [comment]
I have been testing updated script this morning. The script works as intended. The videos that are playing are not shorter/longer than set values.

A different problem of which I was unaware now occurs :
Script plays same video twice, then changes to new one, than plays the first and new one inexchangeably

What I tried:
all combinations of next options:
     -> changing `invidious_instance`
     -> `keep_playlist_on_select=yes` / `no`

Maybe this is related to cookies? How can I create them and where to put them? I run Linux.

**Comment by FatalError93** [comment]
> I have been testing updated script this morning. The script works as intended. The videos that are playing are not shorter/longer than set values.
> 
> A different problem of which I was unaware now occurs : Script plays same video twice, then changes to new one, than plays the first and new one inexchangeably
> 
> What I tried: all combinations of next options: -> changing `invidious_instance` -> `keep_playlist_on_select=yes` / `no`
> 
> Maybe this is related to cookies? How can I create them and where to put them? I run Linux.

Also note this happens if I manually add few songs to be played next - some videos are still played twice and then selected few videos are played again after last one.

**Comment by cvzi** [comment]
Can you give me a video url where it happens?

**Comment by FatalError93** [comment]
> Can you give me a video url where it happens?

Ok what I discovered is that this happens only when I play url from some of invidious instances, however when I use official youtube link this doesn't happen, which leads me to believe that latter issue is indeed connected to cookies. What I suggest is to close this issue as feature request is successfully implemented.
