### ISSUE TITLE
Do I also need to set cookie attribute in youtube-upnext.conf

### ISSUE THREAD

**Issue by timeday1102** [cvzi/mpv-youtube-upnext#34]
If I set "ytdl-raw-options-append = "cookies-from-browser=edge" in file mpv.conf, do I also need to set cookie attribute in youtube-upnext.conf?

**Comment by cvzi** [comment]
The script can only read .txt cookie files. So yes, if you want personal recommendations or you are watching videos that require a login, you also need to set the cookie attribute in the script.

You can create a .txt cookie file as described in this issue:
https://github.com/cvzi/mpv-youtube-upnext/issues/8#issuecomment-1059604272

I will check if it possible to adapt the script to work with "cookies-from-browser".

**Comment by timeday1102** [comment]
> The script can only read .txt cookie files. So yes, if you want personal recommendations or you are watching videos that require a login, you also need to set the cookie attribute in the script.
> 
> You can create a .txt cookie file as described in this issue: [#8 (comment)](https://github.com/cvzi/mpv-youtube-upnext/issues/8#issuecomment-1059604272)
> 
> I will check if it possible to adapt the script to work with "cookies-from-browser".

Thank you

**Comment by cvzi** [comment]
I don't see an easy way to directly include cookies from browser in the script.
However it seems to work to just do this:
```
mpv --ytdl-raw-options-append=cookies-from-browser=edge --ytdl-raw-options-append=cookies=C:\Users\user\my\cookies.txt
```
This writes the cookies from the browser to the cookies.txt file and then the script can access load the cookies from there.
