### ISSUE TITLE
upnext failed: error=2

### ISSUE THREAD

**Issue by Lc4B** [cvzi/mpv-youtube-upnext#38]
I updated a few things and now every YouTube link I load gives me error 2
![error 2](https://github.com/cvzi/mpv-youtube-upnext/assets/149880036/c67689b8-cd26-4539-b281-ab08a41e9c55)

exe files:
curl 8.6.0
mpv v0.37.0-382-g74b4c3c5
yt-dlp 2023.12.30
wget 1.21.4 (not updated)

**Comment by cvzi** [comment]
Could you check if this version works:
https://github.com/cvzi/mpv-youtube-upnext/blob/patch-cookie-jar/youtube-upnext.lua

**Comment by Lc4B** [comment]
> Could you check if this version works: https://github.com/cvzi/mpv-youtube-upnext/blob/patch-cookie-jar/youtube-upnext.lua
It works, it doesn't give me any more errors
