### ISSUE TITLE
The script displays only 11 videos

### ISSUE THREAD

**Issue by Niotferdi** [cvzi/mpv-youtube-upnext#4]
When I press the hotkey of my choice, only one video is displayed. And when you go to it, and press the key again, no more videos are displayed. Although the screenshot of the script from its GitHub page shows how the script displays several video titles, and its functions themselves are designed for just that.
I tried different videos as I thought it was due to YouTube's access restrictions - it didn't help. Updated youtube-dl and wget - everything remained the same.

**Comment by cvzi** [comment]
It will only show one video for most videos. It has been like that for a few months now, the Youtube page does not contain more videos anymore. I guess it will stay that way.

The issue that after one time there are no videos displayed is a bug, but I cannot reproduce it right now.
I assume the Youtube page has changed and Youtube is slowly rolling out an update. You get the new version of the page while I still get the old version.

**Comment by Admicos** [comment]
I was able to get this working but using the Invidious project's API: https://github.com/Admicos/mpv-youtube-upnext/commit/8f08ee82cd4327c7583d8e3bc6fad4085852fb90

I am not going to send a PR because this specific commit is intended as a quick hack to get it working on my machine and will probably break after a day or so. Just putting this on here in case it's useful

**Comment by cvzi** [comment]
I am unfamiliar with Invidious, why do you think it will break soon?

**Comment by Admicos** [comment]
> I am unfamiliar with Invidious,

https://github.com/iv-org/invidious

It's an alternative web interface to YouTube, which also provides a
proper API for use on things like this.

> why do you think it will break soon?

I wasn't *that* serious on that. It's just that the code is pretty
fragile and ugly, as my only concern was to just hack it into a usable
state for my personal use.

Other than that, Invidious instances tend to be slow and get
rate-limited by YouTube pretty frequently, so even if my code was
reliable, it might still fail occasionally.

**Comment by cvzi** [comment]
I see. I guess, we could still add it as a fallback. If it fails to extract the data from the youtube page, it could fallback to using one or several of their instances.

Extracting the JSON from the youtube HTML is not exactly pretty either, and I didn't think it would work for long when I wrote it, but it has worked for almost a year now.

I just quickly looked over the Youtube HTML and these recommendations from invidious are also in the HTML, although not exactly the same ones as on Invidious (probably Youtube randomized or personalized them). 
But the script is still working fine for me, so I'll wait until it breaks for me as well before I start to change anything in the script.

**Comment by icha1** [comment]
It is possible to get the playlist with youtub-dl 
`youtube-dl -j  --flat-playlist "playlist-url"` 

-j option is for json format

**Comment by cvzi** [comment]
> It is possible to get the playlist with youtub-dl
> `youtube-dl -j --flat-playlist "playlist-url"`

Unfortunately, it does not contain the recommendations if you do it with the url of a single video

**Comment by cvzi** [comment]
So today it started to sporadically fail for me too. I have updated the script. Please go ahead and test the new version.

I used @Admicos code from Admicos@8f08ee8 in 9b95bddfff08b6eea388c6c2c5288f195f795dc9 to implement a fallback to Invidious API. 

`invidious.snopyta.org` didn't work for me 😜 It works in the browser but with wget I receive an error 404. I used `invidious.xyz` instead. There is a list of all the instances here: https://instances.invidio.us/

**Comment by Niotferdi** [comment]
Thanks a lot for your work. The updated script displays multiple videos.

But there are 11 of them... While there are more than 11 videos in the recommendations on the page. Wouldn't it be difficult for you to increase the maximum number of videos displayed through the script and add the setting of their number to the configuration file?

**Comment by cvzi** [comment]
It should now shows all recommendations. Depending on the video that's seems to be 15-20.

**Comment by Niotferdi** [comment]
Yes, more recommendations are now displayed.

Once again, thank you for developing this great video player!
The topic can be closed.
