### ISSUE TITLE
Enhancement: open menu without updating list

### ISSUE THREAD

**Issue by icha1** [cvzi/mpv-youtube-upnext#5]
Is it possible to have a short key for just opening the playlist menu (without updating it)? Because, if I am correct, the current behavior of ctrl+u is to update + show the playlist. But sometimes I need the menu for selection without updating the playlist.

**Comment by cvzi** [comment]
I don't use playlists at all, I only play single videos, so I am not sure what the behavior is with playlists. I will check it out

**Comment by icha1** [comment]
Oh sorry, I didn't mean a youtube playlist. I meant the upnext-menu (playlist).

**Comment by cvzi** [comment]
Could you explain in more detail, I don't understand it 

This is the behavior that should currently happen:
1.    Play any youtube video
2.    Press ctrl+u
3.    The menu shows a list of the recommended videos
     *  Select one video and press Enter -> the selected video is played immediately
     *  Don't press Enter -> the menu is hidden after a few seconds and nothing else happens
