### ISSUE TITLE
mpv window reset with next song

### ISSUE THREAD

**Issue by johnson-stuart** [cvzi/mpv-youtube-upnext#6]
On Windows.

Going to next video causes the window to reset back to default size and I have to manually rescale it again.

Any simple fix for this?

**Comment by cvzi** [comment]
It seems to happen only when the next video has a different size. If the next video has exactly the same size, then the window size does also not change back to the default scaling. 

Scrolling through the mpv documentation, I found these properties:

https://mpv.io/manual/stable/#command-interface-dwidth
> **dwidth, dheight**
> Video display size. This is the video size after filters and aspect scaling have been applied. The actual video window size can still be different from this, e.g. if the user resized the video window manually.

https://mpv.io/manual/stable/#command-interface-window-scale
> **window-scale (RW)**
> Window size multiplier. Setting this will resize the video window to the values contained in `dwidth` and `dheight` multiplied with the value set with this property. Setting 1 will resize to original video size (or to be exact, the size the video filters output). 2 will set the double size, 0.5 halves the size.`

As far as I understand, using these properties, it should be possible to "remember" the window size i.e. scale the next video to the same or smaller size than the window.

I will test it when I find some time

**Comment by cvzi** [comment]
I added a first try t, it seems to work fine for me. 

It saves the windows width when you resize the window and restores that width on the next videos.
When a new video starts the window does still go to default size for a short time (<1 second), before the script restores the old size.

I have **disabled it by default**, you need to enable the option `restore_window_width` in the script or in the config file
