### ISSUE TITLE
Error with unset TEMP environment variable

### ISSUE THREAD

**Issue by Croissong** [cvzi/mpv-youtube-upnext#7]
Hi!

Starting mpv without having the `TEMP` env var set produces the following lua error on startup:
```
[youtube_upnext] Lua error:  youtube-upnext.lua:157: attempt to concatenate a nil value
```

The culprit seems to be:
```
opts.cookies = os.getenv("TEMP") .. "/youtube-upnext.cookies"
```

Running mpv with `TEMP=/tmp mpv ...` fixes it.
I have no idea what's the cross-platform way of creating a tmp file in lua, but I don't think `TEMP` can be assumed.
I am on archlinux btw ;D

PS: Awesome project :heart:

**Comment by cvzi** [comment]
Thanks!
I remember Lua has a built-in function to create temporary files, but it didn't work on Windows. Maybe I can try to use that built-in function if the TEMP is not set.

**Comment by Croissong** [comment]
best i could come up with is
```
opts.cookies = io.tmpfile()
msg.warn("Created a temporary cookies jar file. To hide this warning, set a cookies file in the script configuration")
```
This works on linux.

The returned file has no real path that can be logged.
But since the user is encouraged to configure a cookies anyway, i think it's fine.

**Comment by cvzi** [comment]
Thanks, then I will add that
