### ISSUE TITLE
Integration with google account

### ISSUE THREAD

**Issue by RafeeDaBoy** [cvzi/mpv-youtube-upnext#8]
It'd be great if it could be connected with your Google account so that it can provide suggestions based on your personal YouTube recommendations.

**Comment by cvzi** [comment]
It is possible to login with [yt-dlp](https://github.com/yt-dlp/yt-dlp) and a `cookie.txt` file like this:

1. Login to youtube.com in your browser
2. Run this command in a terminal: 
   `yt-dlp --cookies=cookies.txt --verbose --cookies-from-browser=chrome https://www.youtube.com/watch?v=-D1WVfZaMqc` 
   Replace `chrome` with your browser. Currently supported browsers are: brave, chrome, chromium, edge, firefox, opera, safari, vivaldi. More info at the yt-dlp documentation: https://github.com/yt-dlp/yt-dlp. 
   You can use any Youtube video URL. 
   The command retrieves the cookies from your browser and stores them in a new `cookies.txt` file. Then it starts to download the video, you can cancel the download with CTRL+C.
3. Now move the new `cookies.txt` somewhere you like and then put the path to the file in the config: If you use the config file here: https://github.com/cvzi/mpv-youtube-upnext/blob/master/youtube-upnext.conf#L52-L57 or directly in the script here: https://github.com/cvzi/mpv-youtube-upnext/blob/master/youtube-upnext.lua#L64-L71

**Comment by RafeeDaBoy** [comment]
It's working like a charm, thanks!
