### ISSUE TITLE
Detect/prevent recommendation loops

### ISSUE THREAD

**Issue by ribbanya** [cvzi/mpv-youtube-upnext#9]
Currently it seems likely that based on YouTube's recommendations, video A leads to video B, which leads back to video A, causing an infinite loop. [This Stack Overlow answer](https://unix.stackexchange.com/a/616295) provides a couple different algorithms to prevent loops.

Ideally, instead of strictly banning each ID ever encountered (as the SO answer does), it would only keep track of X number of videos, or only remember an ID for T amount of time, either which would be configured by the user.

**Comment by cvzi** [comment]
I think if the script kept the watched IDs in the normal memory of the script, whenever mpv is restarted the IDs would be reset. That would probably be the easiest way to do it and seems intuitive.

**Comment by cvzi** [comment]
I did a few tests with music videos, where it seems to happen regularly and it worked as far as I saw.

It does not work when a video is watched again that was watched already. That's because the results are cached and the script just uses the same result as the first time the video was watched. I don't think that should be a problem?

**Comment by ribbanya** [comment]
> It does not work when a video is watched again that was watched already.

Sorry, I'm not entirely sure what you mean by this. Are you saying if you watch a video again manually, it won't filter the next recommendation?

**Comment by cvzi** [comment]
Yes exactly

**Comment by ribbanya** [comment]
Seems fine if it's all in memory.

**Comment by ribbanya** [comment]
Thanks for implementing this so quickly. If I have any problems with it I'll just submit a PR instead of an issue.
